// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_UpScreen.h"
#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "GUI.h"
///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_holol_png);    // assets/holol.png
LV_IMG_DECLARE(ui_img_1824453990);    // assets/电压1.png
LV_IMG_DECLARE(ui_img_1834844716);    // assets/电流1.png
LV_IMG_DECLARE(ui_img_1296341935);    // assets/电功率1.png
LV_IMG_DECLARE(ui_img_1617932213);    // assets/温度 ().png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
