// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_PowerOpen2 = NULL;
lv_obj_t * ui_Power2 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_TemVal2 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_VinVal2 = NULL;
lv_obj_t * ui_SpinboxCurr2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_SpinboxVolt2 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 60);
    lv_obj_set_height(ui_Button2, 20);
    lv_obj_set_x(ui_Button2, 129);
    lv_obj_set_y(ui_Button2, 104);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xD67575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "BACK");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_Screen2);
    lv_obj_set_width(ui_Chart1, 316);
    lv_obj_set_height(ui_Chart1, 170);
    lv_obj_set_x(ui_Chart1, 0);
    lv_obj_set_y(ui_Chart1, 4);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 15);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 256);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 256);
    lv_chart_set_div_line_count(ui_Chart1, 10, 15);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 5, 0, 0, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0x1D9F06), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 131);
    lv_obj_set_y(ui_Switch2, -103);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Panel10 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel10, 112);
    lv_obj_set_height(ui_Panel10, 34);
    lv_obj_set_x(ui_Panel10, 103);
    lv_obj_set_y(ui_Panel10, -101);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x3900FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel10, lv_color_hex(0x3900FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerOpen2 = lv_switch_create(ui_Panel10);
    lv_obj_set_width(ui_PowerOpen2, 50);
    lv_obj_set_height(ui_PowerOpen2, 25);
    lv_obj_set_x(ui_PowerOpen2, 26);
    lv_obj_set_y(ui_PowerOpen2, 0);
    lv_obj_set_align(ui_PowerOpen2, LV_ALIGN_CENTER);

    ui_Power2 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Power2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Power2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Power2, -25);
    lv_obj_set_y(ui_Power2, 0);
    lv_obj_set_align(ui_Power2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Power2, "OFF");
    lv_obj_set_style_text_color(ui_Power2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Power2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Power2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel5, 69);
    lv_obj_set_height(ui_Panel5, 34);
    lv_obj_set_x(ui_Panel5, 10);
    lv_obj_set_y(ui_Panel5, -101);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Panel5);
    lv_img_set_src(ui_Image2, &ui_img_1617932213);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -20);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 220);

    ui_TemVal2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_TemVal2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemVal2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemVal2, 10);
    lv_obj_set_y(ui_TemVal2, -1);
    lv_obj_set_align(ui_TemVal2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemVal2, "00");
    lv_obj_set_style_text_color(ui_TemVal2, lv_color_hex(0xFE0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemVal2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemVal2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel9, 132);
    lv_obj_set_height(ui_Panel9, 34);
    lv_obj_set_x(ui_Panel9, -92);
    lv_obj_set_y(ui_Panel9, -102);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -33);
    lv_obj_set_y(ui_Label5, 0);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Vin:");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x1100FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VinVal2 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_VinVal2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VinVal2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VinVal2, 28);
    lv_obj_set_y(ui_VinVal2, 0);
    lv_obj_set_align(ui_VinVal2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VinVal2, "00V");
    lv_obj_set_style_text_color(ui_VinVal2, lv_color_hex(0xCFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VinVal2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VinVal2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinboxCurr2 = lv_spinbox_create(ui_Screen2);
    lv_obj_set_width(ui_SpinboxCurr2, 124);
    lv_obj_set_height(ui_SpinboxCurr2, 26);
    lv_obj_set_x(ui_SpinboxCurr2, 30);
    lv_obj_set_y(ui_SpinboxCurr2, 105);
    lv_obj_set_align(ui_SpinboxCurr2, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_SpinboxCurr2, 4, 2);
    lv_spinbox_set_range(ui_SpinboxCurr2, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_SpinboxCurr2, 1 - 1);
    lv_obj_set_style_text_color(ui_SpinboxCurr2, lv_color_hex(0x00D5FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxCurr2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpinboxCurr2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpinboxCurr2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_SpinboxCurr2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -34);
    lv_obj_set_y(ui_Label6, 9);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Cset:");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x00FF2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinboxVolt2 = lv_spinbox_create(ui_Screen2);
    lv_obj_set_width(ui_SpinboxVolt2, 124);
    lv_obj_set_height(ui_SpinboxVolt2, 26);
    lv_obj_set_x(ui_SpinboxVolt2, -96);
    lv_obj_set_y(ui_SpinboxVolt2, 105);
    lv_obj_set_align(ui_SpinboxVolt2, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_SpinboxVolt2, 4, 2);
    lv_spinbox_set_range(ui_SpinboxVolt2, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_SpinboxVolt2, 1 - 1);
    lv_obj_set_style_text_color(ui_SpinboxVolt2, lv_color_hex(0xCFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxVolt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpinboxVolt2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpinboxVolt2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_SpinboxVolt2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -34);
    lv_obj_set_y(ui_Label7, 8);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Vset:");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x00FF2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
		lv_obj_add_event_cb(ui_Screen2, Focus_On_Screen2, LV_EVENT_SCREEN_LOADED, NULL);
		lv_obj_add_event_cb(ui_PowerOpen2, Switch2_State_Changed, LV_EVENT_VALUE_CHANGED, NULL);
		
		// 1. 开启单行模式 (防止滚动)
		lv_textarea_set_one_line(ui_SpinboxVolt2, true);
		lv_textarea_set_one_line(ui_SpinboxCurr2, true);

		// 2. 设置顶部内边距 (垂直居中)
		lv_obj_set_style_pad_top(ui_SpinboxVolt2, 7, LV_PART_MAIN); 
		lv_obj_set_style_pad_top(ui_SpinboxCurr2, 7, LV_PART_MAIN); 

		// 3. 标签也要跟着往下挪，保持水平对齐
		// y 轴偏移从 2 改为 5
		lv_obj_align(ui_Label7, LV_ALIGN_TOP_LEFT, -5, 2); // Vset
		lv_obj_align(ui_Label6, LV_ALIGN_TOP_LEFT, -5, 2); // Cset

		// 4. 底部内边距清零 (防止溢出)
		lv_obj_set_style_pad_bottom(ui_SpinboxVolt2, 0, LV_PART_MAIN);
		lv_obj_set_style_pad_bottom(ui_SpinboxCurr2, 0, LV_PART_MAIN);

		// 5. 再次确认禁用滚动条
		lv_obj_clear_flag(ui_SpinboxVolt2, LV_OBJ_FLAG_SCROLLABLE);
		lv_obj_clear_flag(ui_SpinboxCurr2, LV_OBJ_FLAG_SCROLLABLE);


}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Button2 = NULL;
    ui_Label1 = NULL;
    ui_Chart1 = NULL;
    ui_Switch2 = NULL;
    ui_Panel10 = NULL;
    ui_PowerOpen2 = NULL;
    ui_Power2 = NULL;
    ui_Panel5 = NULL;
    ui_Image2 = NULL;
    ui_TemVal2 = NULL;
    ui_Panel9 = NULL;
    ui_Label5 = NULL;
    ui_VinVal2 = NULL;
    ui_SpinboxCurr2 = NULL;
    ui_Label6 = NULL;
    ui_SpinboxVolt2 = NULL;
    ui_Label7 = NULL;

}
