// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_PowerOpen2;
extern lv_obj_t * ui_Power2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_TemVal2;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_VinVal2;
extern lv_obj_t * ui_SpinboxCurr2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_SpinboxVolt2;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

