// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_VoltVal = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_CurrVal = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_PowerVal = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_VinVal = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_TemVal = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_PowerOpen = NULL;
lv_obj_t * ui_Power = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_TotalAh = NULL;
lv_obj_t * ui_TotalWh = NULL;
lv_obj_t * ui_SpinboxVolt = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_SpinboxCurr = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Roller5 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 60);
    lv_obj_set_height(ui_Button1, 33);
    lv_obj_set_x(ui_Button1, 129);
    lv_obj_set_y(ui_Button1, 100);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "WAVE");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 180);
    lv_obj_set_height(ui_Panel1, 55);
    lv_obj_set_x(ui_Panel1, -68);
    lv_obj_set_y(ui_Panel1, -55);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VoltVal = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_VoltVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VoltVal, 19);
    lv_obj_set_y(ui_VoltVal, 0);
    lv_obj_set_align(ui_VoltVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltVal, "00.000V");
    lv_obj_set_style_text_color(ui_VoltVal, lv_color_hex(0xCFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VoltVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VoltVal, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image5, &ui_img_1824453990);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -68);
    lv_obj_set_y(ui_Image5, 2);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 300);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 180);
    lv_obj_set_height(ui_Panel2, 55);
    lv_obj_set_x(ui_Panel2, -68);
    lv_obj_set_y(ui_Panel2, 2);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrVal = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_CurrVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrVal, 19);
    lv_obj_set_y(ui_CurrVal, 0);
    lv_obj_set_align(ui_CurrVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrVal, "00.000A");
    lv_obj_set_style_text_color(ui_CurrVal, lv_color_hex(0x00D5FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrVal, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Image6, &ui_img_1834844716);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -68);
    lv_obj_set_y(ui_Image6, 2);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 300);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 180);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_x(ui_Panel3, -68);
    lv_obj_set_y(ui_Panel3, 57);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerVal = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_PowerVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PowerVal, 19);
    lv_obj_set_y(ui_PowerVal, 0);
    lv_obj_set_align(ui_PowerVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerVal, "00.00W");
    lv_obj_set_style_text_color(ui_PowerVal, lv_color_hex(0x001EF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PowerVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PowerVal, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_Image7, &ui_img_1296341935);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -68);
    lv_obj_set_y(ui_Image7, 2);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 300);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 132);
    lv_obj_set_height(ui_Panel6, 34);
    lv_obj_set_x(ui_Panel6, -92);
    lv_obj_set_y(ui_Panel6, -102);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -33);
    lv_obj_set_y(ui_Label17, 0);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Vin:");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x1100FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VinVal = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_VinVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VinVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VinVal, 28);
    lv_obj_set_y(ui_VinVal, 0);
    lv_obj_set_align(ui_VinVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VinVal, "00V");
    lv_obj_set_style_text_color(ui_VinVal, lv_color_hex(0xCFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VinVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VinVal, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 69);
    lv_obj_set_height(ui_Panel7, 34);
    lv_obj_set_x(ui_Panel7, 10);
    lv_obj_set_y(ui_Panel7, -101);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Panel7);
    lv_img_set_src(ui_Image4, &ui_img_1617932213);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -20);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 220);

    ui_TemVal = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_TemVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemVal, 10);
    lv_obj_set_y(ui_TemVal, -1);
    lv_obj_set_align(ui_TemVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemVal, "00");
    lv_obj_set_style_text_color(ui_TemVal, lv_color_hex(0xFE0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemVal, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 112);
    lv_obj_set_height(ui_Panel8, 34);
    lv_obj_set_x(ui_Panel8, 103);
    lv_obj_set_y(ui_Panel8, -101);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x3900FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel8, lv_color_hex(0x3900FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerOpen = lv_switch_create(ui_Panel8);
    lv_obj_set_width(ui_PowerOpen, 50);
    lv_obj_set_height(ui_PowerOpen, 25);
    lv_obj_set_x(ui_PowerOpen, 26);
    lv_obj_set_y(ui_PowerOpen, 0);
    lv_obj_set_align(ui_PowerOpen, LV_ALIGN_CENTER);

    ui_Power = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Power, -25);
    lv_obj_set_y(ui_Power, 0);
    lv_obj_set_align(ui_Power, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Power, "OFF");
    lv_obj_set_style_text_color(ui_Power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Power, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel11, 133);
    lv_obj_set_height(ui_Panel11, 90);
    lv_obj_set_x(ui_Panel11, 92);
    lv_obj_set_y(ui_Panel11, -37);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, -26);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Total enegry");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xCD00FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TotalAh = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_TotalAh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TotalAh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TotalAh, 0);
    lv_obj_set_y(ui_TotalAh, 3);
    lv_obj_set_align(ui_TotalAh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TotalAh, "0000.000AH");
    lv_obj_set_style_text_color(ui_TotalAh, lv_color_hex(0x00D5FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TotalAh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TotalAh, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TotalWh = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_TotalWh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TotalWh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TotalWh, 0);
    lv_obj_set_y(ui_TotalWh, 26);
    lv_obj_set_align(ui_TotalWh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TotalWh, "0000.000WH");
    lv_obj_set_style_text_color(ui_TotalWh, lv_color_hex(0x00FD40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TotalWh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TotalWh, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinboxVolt = lv_spinbox_create(ui_Screen1);
    lv_obj_set_width(ui_SpinboxVolt, 124);
    lv_obj_set_height(ui_SpinboxVolt, 33);
    lv_obj_set_x(ui_SpinboxVolt, -96);
    lv_obj_set_y(ui_SpinboxVolt, 100);
    lv_obj_set_align(ui_SpinboxVolt, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_SpinboxVolt, 4, 2);
    lv_spinbox_set_range(ui_SpinboxVolt, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_SpinboxVolt, 1 - 1);
    lv_obj_set_style_text_color(ui_SpinboxVolt, lv_color_hex(0xCFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpinboxVolt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpinboxVolt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
		
		
		
    ui_Label11 = lv_label_create(ui_SpinboxVolt);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -34);
    lv_obj_set_y(ui_Label11, 3);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Vset:");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x00FF2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinboxCurr = lv_spinbox_create(ui_Screen1);
    lv_obj_set_width(ui_SpinboxCurr, 124);
    lv_obj_set_height(ui_SpinboxCurr, 33);
    lv_obj_set_x(ui_SpinboxCurr, 30);
    lv_obj_set_y(ui_SpinboxCurr, 100);
    lv_obj_set_align(ui_SpinboxCurr, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_SpinboxCurr, 4, 2);
    lv_spinbox_set_range(ui_SpinboxCurr, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_SpinboxCurr, 1 - 1);
    lv_obj_set_style_text_color(ui_SpinboxCurr, lv_color_hex(0x00D5FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxCurr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpinboxCurr, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpinboxCurr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_SpinboxCurr);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -34);
    lv_obj_set_y(ui_Label4, 3);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Cset:");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x00FF2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller5 = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_Roller5, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller5, 133);
    lv_obj_set_height(ui_Roller5, 69);
    lv_obj_set_x(ui_Roller5, 92);
    lv_obj_set_y(ui_Roller5, 44);
    lv_obj_set_align(ui_Roller5, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
		lv_obj_add_event_cb(ui_Screen1, Focus_On_Screen1, LV_EVENT_SCREEN_LOADED, NULL);
		lv_obj_add_event_cb(ui_PowerOpen, Switch_State_Changed, LV_EVENT_VALUE_CHANGED, NULL);
		
		

		// 1. 开启单行模式 (防止滚动的基础)
		lv_textarea_set_one_line(ui_SpinboxVolt, true);
		lv_textarea_set_one_line(ui_SpinboxCurr, true);

		// 2. 设置顶部内边距 (实现垂直居中)
		// 这里填你算出来的值，比如 7 或者 8
		lv_obj_set_style_pad_top(ui_SpinboxVolt, 2, LV_PART_MAIN); 
		lv_obj_set_style_pad_top(ui_SpinboxCurr, 2, LV_PART_MAIN);
		lv_obj_align(ui_Label11, LV_ALIGN_TOP_LEFT, 2, -1);
		lv_obj_align(ui_Label4, LV_ALIGN_TOP_LEFT, 2, -1);

		// 3. 底部内边距设为 0 (防止总高度溢出导致滚动)
		lv_obj_set_style_pad_bottom(ui_SpinboxVolt, 0, LV_PART_MAIN);
		lv_obj_set_style_pad_bottom(ui_SpinboxCurr, 0, LV_PART_MAIN);

		// 4. 再次确认禁用了滚动条
		lv_obj_clear_flag(ui_SpinboxVolt, LV_OBJ_FLAG_SCROLLABLE);
		lv_obj_clear_flag(ui_SpinboxCurr, LV_OBJ_FLAG_SCROLLABLE);


}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Button1 = NULL;
    ui_Label2 = NULL;
    ui_Panel1 = NULL;
    ui_VoltVal = NULL;
    ui_Image5 = NULL;
    ui_Panel2 = NULL;
    ui_CurrVal = NULL;
    ui_Image6 = NULL;
    ui_Panel3 = NULL;
    ui_PowerVal = NULL;
    ui_Image7 = NULL;
    ui_Panel6 = NULL;
    ui_Label17 = NULL;
    ui_VinVal = NULL;
    ui_Panel7 = NULL;
    ui_Image4 = NULL;
    ui_TemVal = NULL;
    ui_Panel8 = NULL;
    ui_PowerOpen = NULL;
    ui_Power = NULL;
    ui_Panel11 = NULL;
    ui_Label20 = NULL;
    ui_TotalAh = NULL;
    ui_TotalWh = NULL;
    ui_SpinboxVolt = NULL;
    ui_Label11 = NULL;
    ui_SpinboxCurr = NULL;
    ui_Label4 = NULL;
    ui_Roller5 = NULL;

}
