// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_VoltVal;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_CurrVal;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_PowerVal;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_VinVal;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_TemVal;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_PowerOpen;
extern lv_obj_t * ui_Power;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_TotalAh;
extern lv_obj_t * ui_TotalWh;
extern lv_obj_t * ui_SpinboxVolt;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_SpinboxCurr;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Roller5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

