// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_UpScreen = NULL;
lv_obj_t * ui_Image11 = NULL;
// event funtions
void ui_event_UpScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 1500, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_UpScreen_screen_init(void)
{
    ui_UpScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_UpScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_UpScreen);
    lv_img_set_src(ui_Image11, &ui_img_holol_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, -63);
    lv_obj_set_y(ui_Image11, 0);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image11, 350);

    lv_obj_add_event_cb(ui_UpScreen, ui_event_UpScreen, LV_EVENT_ALL, NULL);

}

void ui_UpScreen_screen_destroy(void)
{
    if(ui_UpScreen) lv_obj_del(ui_UpScreen);

    // NULL screen variables
    ui_UpScreen = NULL;
    ui_Image11 = NULL;

}
