// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_UPSCREEN_H
#define UI_UPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_UpScreen
extern void ui_UpScreen_screen_init(void);
extern void ui_UpScreen_screen_destroy(void);
extern void ui_event_UpScreen(lv_event_t * e);
extern lv_obj_t * ui_UpScreen;
extern lv_obj_t * ui_Image11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

